### ISSUE TITLE
Project empty

### ISSUE THREAD

**Issue by farishkash** [psvirdee/Dasmoto-s-Arts-Crafts#1]
There is no html in here, if you push an updated version, leave a comment here and I will review it.

**Comment by psvirdee** [comment]
Hi Farish,

Apologise, I have now pulled the files into the master branch. I am still a little unclear how this all works but I hope you can now see the files.

Kind Regards 

Pav

**Comment by psvirdee** [comment]
Hi Farish,

Could you also help me understand why when I go to "https://psvirdee.github.io/Dasmoto-s-Arts-Crafts/" the css styles are not applied?

Kind Regards

Pav

**Comment by farishkash** [comment]
Looks like you fixed this part, going to do my review.
