### ISSUE TITLE
How to avoid repetition in your css

### ISSUE THREAD

**Issue by farishkash** [psvirdee/Dasmoto-s-Arts-Crafts#3]
```
 font-size: 32px;
  font-weight: bold;
  color: white;

```
So this you are using a few times.

Just like how you handle your font family you can do the same with these 3 by using this.

```
h2 {
 font-size: 32px;
  font-weight: bold;
  color: white;
}
```

That way the classes only focus on changing background color.

**Comment by psvirdee** [comment]
Thank you. Appreciate the feedback and will look to incorporate going forward.
