### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [psvirdee/Dasmoto-s-Arts-Crafts#4]
Overall good project.

I look for a couple items here.  First did you use any divs to manage your code.  You could have gone further but you did use a div for the top section which is great.  We can move each section into its own div also, but for this first project isn't as needed.  You will be using divs heavily in the later projects.

Second I look for repetition in your css.  The goal here reinforce the idea that you should look for efficiency where possible.  As the projects get larger some of these short cuts will save you a lot of lines.  The later projects are around 300-500 lines of css so every bit helps.  Also the less lines you have type, the less time you spend looking for a bug in your css.

As a challenge go to flexboxfroggy.com, see how far you can get.  The later projects uses flexbox heavily and this will help prepare you for them.

**Comment by psvirdee** [comment]
Awesome, thank you for taking the time to review. I will have a play at flexboxfroggy.
